global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'access-sentinel'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal allows Prometheus inside Docker to connect to uvicorn on host machine
      - targets: ['host.docker.internal:8000']
